### ISSUE TITLE
What is installations step ?

### ISSUE THREAD

**Issue by shrikantpandey13** [EU-ECDC/epitweetr#13]

**Comment by lauespinosa** [comment]
You can find the installation steps in the [vignette](https://cran.r-project.org/web/packages/epitweetr/vignettes/epitweetr-vignette.html).

As a summary:
1. Check that you have all prerequisites for running `epitweetr`
2. Install `epitweetr` from CRAN
2. Launch `epitweetr` Shiny app and go to configuration page
3. Run dependencies, geonames and languages
4. Set up Twitter authentication
4. Activate tweet search and detection pipeline

You can also change other settings in the configuration page (topics and keywords, languages, etc).

Hope this helps!

**Comment by shrikantpandey13** [comment]
Thank very much for your input :) @lauespinosa

**Comment by HORSE-source** [comment]
What is the command for step 3?
