### ISSUE TITLE
Error in geotagging

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#18]
This error frequently happening these days on the epitweetr instance I am running on my laptop (not the Azure one).
![error in running app](https://user-images.githubusercontent.com/23038328/113623234-10d42c80-962c-11eb-9666-40202f07e6fb.PNG)

**Comment by forchard** [comment]
Hi Abdouzster,

To see clearer, could you please share the lines corresponding to the error date on the detect.log file located C:/users/your_username/epitweetr/detect.log  ?

Thanks in advance!

**Comment by Abdouzster** [comment]
Hi Forchard,
The errors listed below.
Thanks,
Abdou
2021-04-05 22:25:01 : Executing task aggregate
Aggregating series country_counts ( 2021-03-29 ) by looking on tweets collected between ( 2021.03.28, 2021.03.29, 2021.03.31, 2021.04.02, 2021.04.04, 2021.04.05 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Failed...
failed while serie country_counts for 2021-03-29   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_261\bin\java" -cp "C:/Users/abdou/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/abdou/Documents/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "C:/Users/abdou/Documents/Twitter/tweets/search" geoPath "C:/Users/abdou/Documents/Twitter/tweets/geolocated" pathFilter ".*2021\.03\.28.*,.*2021\.03\.29.*,.*2021\.03\.31.*,.*2021\.04\.02.*,.*2021\.04\.04.*,.*2021\.04\.05.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-03-29'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt,ar" langNames "English,French,Spanish,Portuguese,Arabic" langPaths "C:/Users/abdou/Documents/Twitter/languages/en.txt.gz,C:/Users/abdou/Documents/Twitter/languages/fr.txt.gz,C:/Users/abdou/Documents/Twitter/languages/es.txt.gz,C:/Users/abdou/Documents/Twitter/languages/pt.txt.gz,C:/Users/abdou/Documents/Twitter/languages/ar.txt.gz"  parallelism 6 params "C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\repl988a687c27.txt" >"C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\file98828ccf9c"' execution failed with error code 1

2021-04-05 22:27:16 : Executing task aggregate
Aggregating series country_counts ( 2021-03-29 ) by looking on tweets collected between ( 2021.03.28, 2021.03.29, 2021.03.31, 2021.04.02, 2021.04.04, 2021.04.05 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Failed...
failed while serie country_counts for 2021-03-29   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_261\bin\java" -cp "C:/Users/abdou/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/abdou/Documents/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "C:/Users/abdou/Documents/Twitter/tweets/search" geoPath "C:/Users/abdou/Documents/Twitter/tweets/geolocated" pathFilter ".*2021\.03\.28.*,.*2021\.03\.29.*,.*2021\.03\.31.*,.*2021\.04\.02.*,.*2021\.04\.04.*,.*2021\.04\.05.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-03-29'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt,ar" langNames "English,French,Spanish,Portuguese,Arabic" langPaths "C:/Users/abdou/Documents/Twitter/languages/en.txt.gz,C:/Users/abdou/Documents/Twitter/languages/fr.txt.gz,C:/Users/abdou/Documents/Twitter/languages/es.txt.gz,C:/Users/abdou/Documents/Twitter/languages/pt.txt.gz,C:/Users/abdou/Documents/Twitter/languages/ar.txt.gz"  parallelism 6 params "C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\repl98836224cab.txt" >"C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\file9881882475b"' execution failed with error code 1

2021-04-05 22:28:17 : Executing task aggregate
Aggregating series country_counts ( 2021-03-29 ) by looking on tweets collected between ( 2021.03.28, 2021.03.29, 2021.03.31, 2021.04.02, 2021.04.04, 2021.04.05 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Failed...
failed while serie country_counts for 2021-03-29   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_261\bin\java" -cp "C:/Users/abdou/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/abdou/Documents/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "C:/Users/abdou/Documents/Twitter/tweets/search" geoPath "C:/Users/abdou/Documents/Twitter/tweets/geolocated" pathFilter ".*2021\.03\.28.*,.*2021\.03\.29.*,.*2021\.03\.31.*,.*2021\.04\.02.*,.*2021\.04\.04.*,.*2021\.04\.05.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-03-29'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt,ar" langNames "English,French,Spanish,Portuguese,Arabic" langPaths "C:/Users/abdou/Documents/Twitter/languages/en.txt.gz,C:/Users/abdou/Documents/Twitter/languages/fr.txt.gz,C:/Users/abdou/Documents/Twitter/languages/es.txt.gz,C:/Users/abdou/Documents/Twitter/languages/pt.txt.gz,C:/Users/abdou/Documents/Twitter/languages/ar.txt.gz"  parallelism 6 params "C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\repl98878387b07.txt" >"C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\file9883b835b"' execution failed with error code 1

2021-04-05 22:32:01 : Executing task aggregate
Aggregating series country_counts ( 2021-03-29 ) by looking on tweets collected between ( 2021.03.28, 2021.03.29, 2021.03.31, 2021.04.02, 2021.04.04, 2021.04.05 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Failed...
failed while serie country_counts for 2021-03-29   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_261\bin\java" -cp "C:/Users/abdou/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/abdou/Documents/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "C:/Users/abdou/Documents/Twitter/tweets/search" geoPath "C:/Users/abdou/Documents/Twitter/tweets/geolocated" pathFilter ".*2021\.03\.28.*,.*2021\.03\.29.*,.*2021\.03\.31.*,.*2021\.04\.02.*,.*2021\.04\.04.*,.*2021\.04\.05.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-03-29'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt,ar" langNames "English,French,Spanish,Portuguese,Arabic" langPaths "C:/Users/abdou/Documents/Twitter/languages/en.txt.gz,C:/Users/abdou/Documents/Twitter/languages/fr.txt.gz,C:/Users/abdou/Documents/Twitter/languages/es.txt.gz,C:/Users/abdou/Documents/Twitter/languages/pt.txt.gz,C:/Users/abdou/Documents/Twitter/languages/ar.txt.gz"  parallelism 6 params "C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\repl9883e815dd0.txt" >"C:\Users\abdou\AppData\Local\Temp\Rtmp4iaSiM\file98812a74291"' execution failed with error code 1

**Comment by forchard** [comment]
Hi  Abdouzster, thanks for this additional information.
I still cannot see the origin of the error, so I have to request you to do some additional step to help you with this.

* **Open an R session** 
* **Initialize epitweetr**
    * `epitweetr::setup_config("C:/Users/abdou/Documents/Twitter") # or whatever your epitweeter folder is`
* **Run epitweeter diagnostics**
    * `View(epitweetr::check_all())` 
* **Reproduce the problem** 
    * `t <- epitweetr::aggregate_tweets()`
 
Thanks in advance!
Francisco

**Comment by lauespinosa** [comment]
Hi Abdou,

Was this issue solved with the new winutils URL?

We have released a new version of epitweetr (0.1.28) in CRAN with the correct winutils URL, in case you need to run epitweetr in another machine or would like to install the latest version of epitweetr: `install.packages('epitweetr')`

**Comment by Abdouzster** [comment]
It leads to abort but it was resolved with just clicking on the Run geotag button. I didn't do the trouble shooting. This error was the laptop instance that was running for a while not in the new instance on the VM

**Comment by lauespinosa** [comment]
Hi Abdou,

Part of the error seems similar to the one in the Azure VM that was solved with the new winutils URL.

Please try:
1. Installing the new version of `epitweetr`
2. Launching the Shiny app
3. Clicking on 'Run dependencies' (you may need to rename the folder 'jars'; otherwise, `epitweetr` may not be able to reinstall all jars again), 'Run geonames' and 'Run languages'.
