### ISSUE TITLE
Several warnings upon start up of Epitweetr in RStudio

### ISSUE THREAD

**Issue by HORSE-source** [EU-ECDC/epitweetr#19]
I'm attempting to run epitweetr in the latest version of RStudio. I use the install function within RStudio to install the epitwitter package and then run the following command:

library(epitweetr)
epitweetr_app("data_dir")

When I run this command, I am given the following shown below.

Listening on http://127.0.0.1:7091
Warning: Couldn't coerce the `start` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `end` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `min` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `max` argument to a date string with format yyyy-mm-dd
Warning in check_series_present() :
  No aggregated series found. Please execute the aggregate task
Warning in check_series_present() :
  No aggregated series found. Please execute the aggregate task
Warning in check_series_present() :
  No aggregated series found. Please execute the aggregate task

When I go to Troubleshoot I'm given the following information:

scheduler	true	
twitter_auth	false	Cannot create a Twitter token, please choose an authentication method on the configuration page
search_running	false	Search loop is not running. On Windows, you can activate it by clicking on the 'activate' Tweet search button on the config page You can also manually run the search loop by executing the following command on a separate R session. epitweetr::search_loop('data_dir')
tweets	false	No tweet files found. Please execute the search loop
os64	true	
java	true	
java64	true	
java_version	true	
winmsvc	true	
detect_activation	true	
detection_running	false	Detection pipeline is not running. On Windows, you can activate it by clicking on the 'activate' detection pipeline button on the config page You can also manually run the detection loop by executing the following command on a separate R session. epitweetr::detect_loop('data_dir')
winutils	false	To run SPARK on Windows you need winutils which is a HADOOP binary, you can download it by running the update dependencies task
java_deps	false	epitweetr needs the dependencies task to run and download all java dependencies
move_from_temp	true	
geonames	false	epitweetr needs geonames to be downloaded and unziped for geolocating tweets. Please run the geonames task of the detection pipeline
languages	false	epitweetr needs languages models to be downloaded for geolocating tweets. Please activate some languages and launch the languages task
geotag	false	No geolocated files found. Please execute the geotag task
aggregate	false	No aggregated series found. Please execute the aggregate task
alerts	false	No alert files found. Please execute the alerts task
pandoc	true	
tex	false	For exporting the PDF report from the dashboard, a tex distribution has to be installed. We suggest to install tinytex with the following commands on an r session: install.packages('tinytex'); tinytex::install_tinytex()

I'm not sure what it is that I'm doing incorrectly, or what steps I am missing. Any help is greatly appreciated.

**Comment by lauespinosa** [comment]
Hello,
Thank you for your message. You are not doing anything wrong, let me guide you on what you should do next 😃 

If you are running `epitweetr` in a Windows machine, you should go to the configuration page of the Shiny app and follow these steps:

**Starting with the left column of the configuration page**
1. Select Twitter authentication: using Twitter account (when saving setting, a windows will be prompt to confirm your credentials) or using Twitter developer app (for this, you should add 'App name', 'API key', 'API secret', 'Access token' and 'Token secret').
2. Change the URL for winutils to: https://github.com/steveloughran/winutils/blob/master/hadoop-3.0.0/bin/winutils.exe
3. Fill in the email settings to send the alerts. 'From' and 'login' are the email address that will be used to send the alerts
4. Click on 'save settings'.

**Continuing with the right column of the configuration page**

5. Modify the topics, if needed, and upload the new Excel topics file to the corresponding section of the configuration page
6. Add or delete new languages as needed. Please do not delete all languages that are included by default since epitweetr may give an error
7. Modify the list of trusted users if needed
8. Add list of subscribers (people who will receive `epitweetr` alerts). You can find more information in the vignette

**Then, you can activate the search and detection pipeline in the configuration page:**

1. Click on 'Run dependencies', 'Run GeoNames' and 'Run languages'
2. Click on 'activate' next to 'Tweet search' and next to 'Detection pipeline'
3. A new command prompt window will appear for each pipeline and a new task will be created in the Task Manager as well.  

The message regarding **tex** relates to the ability of `epitweetr` to download PDFs of the dashboard. In order to do that, you should install a tex distribution. We suggest to install tinytex with the following commands on an r session: `install.packages('tinytex')` and after, `tinytex::install_tinytex()`.

Please let us know if you are not running `epitweetr` in a Windows machine, since the previous steps vary slightly.

**Comment by HORSE-source** [comment]
Hello!

I am indeed running a Windows machine :) 

These steps were very helpful, however, I'm still running into a few issues and I have a few questions. I'll run you through everything that I'm doing.

I open R Studio, install the package for tiny tex and epitweetr and run the app to open up the Shiny app and I'm still receiving:

14612
Loading required package: shiny

Listening on http://127.0.0.1:3696
Warning: Couldn't coerce the `start` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `end` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `min` argument to a date string with format yyyy-mm-dd
Warning: Couldn't coerce the `max` argument to a date string with format yyyy-mm-dd
Warning in check_series_present() :
  No aggregated series found. Please execute the aggregate task
Warning in check_series_present() :
  No aggregated series found. Please execute the aggregate task
Warning in check_series_present() :
  No aggregated series found. Please execute the aggregate task

I follow steps 1-4.

Steps 1-4 were successfully completed. 

Starting at Step 5, I downloaded the topics sheet just to take a look through it and familiarize myself with it, but I don't need to change anything

For Step 6 I don't need to add any new languages, so I skipped this step.

For Step 7, I will be the only user.

For Step 8, I will be the only person receiving the email alerts at this time. 

The next three steps under "Activate the search and detection pipeline in the configuration page:" is where I start having issues. 

Step 1: When I click 'Run dependencies', 'Run GeoNames' and ' Run languages', nothing visibly happens except for what appears to be a screen refresh. 

Step 2: Before clicking clicking 'activate' next to "Tweet Search" and "Detection Pipeline" the status is showing "Stopped". When I click on 'activate' next to 'Tweet Search' and next to 'Detection pipeline' the status still displays as "Stopped. 

Step 3: This step doesn't populate

I restarted Rstudio and reopened epitweetr and the same issue about not being able to coerce the arguments and needing to set the aggregate tasks, populates. 

I went under the troubleshoot tab and the attached photo is what I'm seeing. 
![Epitweetr](https://user-images.githubusercontent.com/80736892/113758127-58a89180-96c8-11eb-9ce1-1be6a89cd8bb.png)


Thank you for your quick reply, I look forward to hearing back from you!

**Comment by lauespinosa** [comment]
Hello @HORSE-source ,

Let me first clarify steps 7 and 8:
- Step 7 refers to a list of Twitter users that you trust. You can change that list if needed. `epitweetr` will tell you if for a specific topic and time/day, any of these trusted users tweeted on that.
- Step 8. Even if you are the only user, you need to include your email here

Regarding the issue with the search and detection pipeline, it can be that the date format of your Windows machine is different than the default date format included in epitweetr. Please try the following:
- Open command prompt (type 'cmd' in the start menu) and write the command `date`. It will give you the date of the machine with a format (e.g. dd-mm-yy).
- You can change this in the configuration page of `epitweetr` at the end of the left column under 'Custom date format'. Add the format that appeared in the 'cmd'.
- Click on 'Save settings'
- Try clicking again on 'activate' next to 'Tweet Search' and 'Detection pipeline'

**Comment by HORSE-source** [comment]
Good afternoon @lauespinosa ,

In relation to steps 7 and 8 that is understood. I have added my email and all relevant information in step 8. 

Command prompt tells me that my date format is mm-dd-yy; I input that format into the custom date section, saved my changes, and closed epitweetr and Rstudio, and reopened. I'm still being prompted with the same error in addition to the aggregate warning as well. 

I click on the activate buttons for 'Tweet Search' and for 'Detection pipeline' and they don't move. I was able to get them both to run by opening a second instance of Rstudio and inputting the following commands:

library(epitweetr)
search_loop("data_dir")

library(epitweetr)
detect_loop("data_dir")

Doing this however doesn't allow me to filter the data by topic, date range, or geolocation. 

Thank you for your continued help, it is much appreciated!

**Comment by lauespinosa** [comment]
Hello @HORSE-source ,

You can open the Task Scheduler Library from the Task Scheduler and check if you have two tasks named 'epitweetr_detect_loop' and 'epitweetr_search_loop', to see if the activate buttons worked.

Can you please clarify what do you mean with not being allowed to filter the data?
If you refer to the `epitweetr` dashboard, you will need to wait at least 1-2 days to have enough data to be shown.

If `epitweetr` is collecting and processing tweets, you should be able to see the following folders with files in 'data_dir': stats, tweets and series. In addition, 'Tweet search' and 'Detection pipeline' should appear as 'Running' in the configuration page.

**Comment by HORSE-source** [comment]
Hello @lauespinosa ,

I opened the Task Scheduler and I do see "epitweetr_detect_loop" and "epitweeter_search_loop"; I opened epitweetr and click the "activate" buttons for "Tweet Search" as well as "Detection pipeline" and the Task Scheduler doesn't show that they are working. 

On the dashboard page I set the Topic, Countries & regions, and the dates. I'm giving the following prompt:

Warning in check_series_present() :
  No aggregated series found. Please execute the aggregate task
  
  I ignore the prompt and I go to the Configuration window where I Run the following: dependencies, GeoNames, languages, geotag, aggregate, and alerts. I then click activate next to Tweet Search and am prompted with:
  
  Warning in shell(tcmd) :
  '
call java -cp "C:/Users/tyler/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;data_dir/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getSampleTweets tweetPath "data_dir/tweets/search" pathFilter ".*2021\.04\.08.*" langCodes "en,fr,es,pt" langNames "English,French,Spanish,Portuguese" langPaths "data_dir/languages/en.txt.gz,data_dir/languages/fr.txt.gz,data_dir/languages/es.txt.gz,data_dir/languages/pt.txt.gz"  geonamesSource "data_dir/geo/allCountries.txt" geonamesDestination "data_dir/geo" geonamesSimplify "TRUE" langIndexPath "data_dir/geo/lang_vectors.index" limit 100 parallelism 8 textCol text langCol lang >"C:\Users\tyler\AppData\Local\Temp\RtmpATpg0H\file1a6c85f7ca0"' execution failed with error code 1

I go back to the dashboard and remove the dates I set from the "Date" section and under period I click Last 7 Days and the program crashes and I am prompted with:

Warning: Error in if: missing value where TRUE/FALSE needed
  49: h
  48: .handleSimpleError
  47: refresh_dashboard_data
  46: <observer>
  45: ..stacktraceon..
  44: contextFunc
  43: env$runWith
  42: force
  41: domain$wrapSync
  40: promises::with_promise_domain
  39: withReactiveDomain
  38: domain$wrapSync
  37: promises::with_promise_domain
  36: ctx$run
  35: run
  34: withCallingHandlers
  33: domain$wrapSync
  32: promises::with_promise_domain
  31: captureStackTraces
  30: withCallingHandlers
  29: shinyCallingHandlers
  28: force
  27: withVisible
  26: withCallingHandlers
  25: domain$wrapSync
  24: promises::with_promise_domain
  23: captureStackTraces
  22: doTryCatch
  21: tryCatchOne
  20: tryCatchList
  19: tryCatch
  18: do
  17: hybrid_chain
  16: flushCallback
  15: FUN
  14: lapply
  13: ctx$executeFlushCallbacks
  12: .getReactiveEnvironment()$flush
  11: flushReact
  10: serviceApp
   9: ..stacktracefloor..
   8: withCallingHandlers
   7: domain$wrapSync
   6: promises::with_promise_domain
   5: captureStackTraces
   4: ..stacktraceoff..
   3: runApp
   2: print.shiny.appobj
   1: <Anonymous>

Screenshot below to show how my session opens:
![image](https://user-images.githubusercontent.com/80736892/114057417-646e9200-9847-11eb-9943-d0dbf5ab9b76.png)

Screenshot of topics, countries and regions, and dates being set
![image](https://user-images.githubusercontent.com/80736892/114057607-8e27b900-9847-11eb-85cd-2bc75b16bf22.png)

I move to the Cofiguration panel and it tells me that several of the tasks are either pending, running, or scheduled. I have NOT clicked Run on any of the options under Detection pipeline. 
![image](https://user-images.githubusercontent.com/80736892/114058135-0c845b00-9848-11eb-9405-ea1671eda054.png)

The configuration panel shows that I have run the search and the pipeline, but i did that from a second instance of R Studio as mentioned in my last response. 

I decided to run the Troubleshoot tool, and this is what I was given:
![image](https://user-images.githubusercontent.com/80736892/114058675-874d7600-9848-11eb-8482-ee88d827e236.png)


Looking forward to your response!

**Comment by lauespinosa** [comment]
Hello @HORSE-source ,

First, please change the winutils URL to https://github.com/steveloughran/winutils/raw/master/hadoop-3.0.0/bin/winutils.exe, and click on 'save settings'. Click on 'Run dependencies', 'Run geonames' and 'Run languages' again.

Once you have activated 'Tweet search' and 'Detection pipeline' again, you can manage these tasks directly in the Task scheduler. There is no need to click again on 'activate' after the tasks are created in the Task scheduler. 

For managing these tasks in the Task scheduler:
- You can check if the tasks are 'running'
- You can stop ('end' and 'deactivate') any of these two tasks
- You can activate them again ('activate' and 'run')

Let us know how it goes.

**Comment by HORSE-source** [comment]
Good afternoon @forchard and @lauespinosa ! 

Thank you for the words of encouragement! This is all very exciting! I followed your steps and got the directory path set up appropriately; now it's running smoothly and the two command prompt windows have populated and are staying open. 

I have updated the winutils URL as instructed, saved settings, which then authenticated my Twitter account. I clicked on 'Run dependencies', 'Run geonames' and 'Run languages'  and the task scheduler shows as running. However Epitweetr isn't showing that its performing any type of task. Typically the console shows results that the program is returning. 

![image](https://user-images.githubusercontent.com/80736892/114097441-e2955d80-9874-11eb-8ba5-9839b5956bfe.png)


Now that we have all that set up, I would like to assess using the dashboard to search for specific topics and date ranges.  The below image shows what I have set the parameters too in the dashboard and the fuckint they performed in Rstudio

![image](https://user-images.githubusercontent.com/80736892/114097905-87179f80-9875-11eb-91cb-d90fd57c17a3.png)


My configuration page currently looks as such:

![image](https://user-images.githubusercontent.com/80736892/114097973-9860ac00-9875-11eb-9b72-a1e289732143.png)


Thank you again, so much, for your continued help with this!!! Looking forward to hearing from you!

**Comment by lauespinosa** [comment]
Hi @HORSE-source ,

You are almost there 😄 

It is normal that you don't see any data in the dashboard since you haven't run the detection pipeline yet (tasks 0 to 5 are either aborted, scheduled or pending, but not 'success'). So there is no data serie created by `epitweetr` that can be shown in the dashboard.

You are collecting tweets, though. You can check this in the folder 'tweets/search' of your epitweetr working directory. If you want to see the tweets collected, you can use this [function](https://github.com/EU-ECDC/epitweetr/discussions/8).

In order to get the detection pipeline working properly, please follow these steps:

1. Install `epitweetr` again, we have just released a new version (0.1.28) that contains the correct winutils URL
2. Rename or delete the folder 'C:/Users/tyler/Documents/data_dir/jars'; otherwise, `epitweetr` won't be able to reinstall all jars
3. Launch `epitweetr` app using the full path: `epitweetr_app('C:/Users/tyler/Documents/data_dir')`
4. In the configuration page, click on 'Run dependencies', 'Run geonames' and 'Run languages'

**Comment by HORSE-source** [comment]
Hey @lauespinosa ! 

Haha thanks for the vote of confidence! 

Okay so the dashboard is used to filter out the data after it has been collected, is that correct? 

In relation to the steps:

1. I have downloaded and installed the new epitweetr and after it installs I attempt to launch the command as you stated and I'm met with an error. Screen shot below:

![image](https://user-images.githubusercontent.com/80736892/114234058-18008080-9933-11eb-8081-5b2a8dd08459.png)

2. I did rename the 'jars' directory as you'll see in the above screenshot

3. This is where I get the error. Instead, I used the following command
library(epitweetr)
epitweetr_app("data_dir")

And it opened epitweetr for me without issue. However, I have a feeling that this is wrong because if this is to be a new install of epitweetr, none of my results should be saved. Is that correct?

**Comment by HORSE-source** [comment]
@lauespinosa 

I am an idiot. I was trying to just run epitweetr_app('C:/Users/tyler/Documents/data_dir') as a solo command without specifying library(epitweetr) first. 

Once I did that I got everything up and running. So, it looks like I'll need to leave this running until it completes everything in its entirety. Is there a way that I can open correspondence with you in email? I have some other questions that pertain to epitweetr that are not related to this thread.

**Comment by lauespinosa** [comment]
@HORSE-source , good that now everything is up and running!

Please ensure that the computer doesn't go to sleep mode or turns off until `epitweetr` has finalised task 2 languages. For the other tasks (3-5), you can turn off the laptop and `epitweetr` will recover, with the limitation of 7 days of Twitter data history from the Twitter Standard Search API.

I will close this thread and you can contact me at laura.espinosa@ecdc.europa.eu
