### ISSUE TITLE
App is not running

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#20]
I am referring here to the epitweetr instance I am running on my laptop. It was running this morning then the computer closed abruptly. when I tried to rerun it. The app is not running at all. it is giving me the following error:
> epitweetr_app("C:/Users/abdou/Documents/Twitter")
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                                            (right here) ------^

**Comment by Abdouzster** [comment]
Here are the errors today from the detect file
2021-04-07 10:52:27 : Executing task aggregate
Aggregating series country_counts ( 2021-03-30 ) by looking on tweets collected between ( 2021.03.29, 2021.03.30, 2021.03.31, 2021.04.02, 2021.04.04, 2021.04.05, 2021.04.06, 2021.04.07 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Failed...
failed while serie country_counts for 2021-03-30   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_261\bin\java" -cp "C:/Users/abdou/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/abdou/Documents/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "C:/Users/abdou/Documents/Twitter/tweets/search" geoPath "C:/Users/abdou/Documents/Twitter/tweets/geolocated" pathFilter ".*2021\.03\.29.*,.*2021\.03\.30.*,.*2021\.03\.31.*,.*2021\.04\.02.*,.*2021\.04\.04.*,.*2021\.04\.05.*,.*2021\.04\.06.*,.*2021\.04\.07.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-03-30'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt,ar" langNames "English,French,Spanish,Portuguese,Arabic" langPaths "C:/Users/abdou/Documents/Twitter/languages/en.txt.gz,C:/Users/abdou/Documents/Twitter/languages/fr.txt.gz,C:/Users/abdou/Documents/Twitter/languages/es.txt.gz,C:/Users/abdou/Documents/Twitter/languages/pt.txt.gz,C:/Users/abdou/Documents/Twitter/languages/ar.txt.gz"  parallelism 6 params "C:\Users\abdou\AppData\Local\Temp\RtmpqufGC7\repl269c43f44d3c.txt" >"C:\Users\abdou\AppData\Local\Temp\RtmpqufGC7\file269c648dca2"' execution failed with error code 1

2021-04-07 10:54:38 : Executing task aggregate
Aggregating series country_counts ( 2021-03-30 ) by looking on tweets collected between ( 2021.03.29, 2021.03.30, 2021.03.31, 2021.04.02, 2021.04.04, 2021.04.05, 2021.04.06, 2021.04.07 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Failed...
failed while serie country_counts for 2021-03-30   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_261\bin\java" -cp "C:/Users/abdou/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/abdou/Documents/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "C:/Users/abdou/Documents/Twitter/tweets/search" geoPath "C:/Users/abdou/Documents/Twitter/tweets/geolocated" pathFilter ".*2021\.03\.29.*,.*2021\.03\.30.*,.*2021\.03\.31.*,.*2021\.04\.02.*,.*2021\.04\.04.*,.*2021\.04\.05.*,.*2021\.04\.06.*,.*2021\.04\.07.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-03-30'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt,ar" langNames "English,French,Spanish,Portuguese,Arabic" langPaths "C:/Users/abdou/Documents/Twitter/languages/en.txt.gz,C:/Users/abdou/Documents/Twitter/languages/fr.txt.gz,C:/Users/abdou/Documents/Twitter/languages/es.txt.gz,C:/Users/abdou/Documents/Twitter/languages/pt.txt.gz,C:/Users/abdou/Documents/Twitter/languages/ar.txt.gz"  parallelism 6 params "C:\Users\abdou\AppData\Local\Temp\RtmpqufGC7\repl269c5a1e6443.txt" >"C:\Users\abdou\AppData\Local\Temp\RtmpqufGC7\file269c708c6747"' execution failed with error code 1

2021-04-07 10:56:14 : Executing task aggregate
Aggregating series country_counts ( 2021-03-30 ) by looking on tweets collected between ( 2021.03.29, 2021.03.30, 2021.03.31, 2021.04.02, 2021.04.04, 2021.04.05, 2021.04.06, 2021.04.07 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Java HotSpot(TM) 64-Bit Server VM warning: CodeCache is full. Compiler has been disabled.
Java HotSpot(TM) 64-Bit Server VM warning: Try increasing the code cache size using -XX:ReservedCodeCacheSize=
Failed...
failed while serie country_counts for 2021-03-30   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_261\bin\java" -cp "C:/Users/abdou/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;C:/Users/abdou/Documents/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "C:/Users/abdou/Documents/Twitter/tweets/search" geoPath "C:/Users/abdou/Documents/Twitter/tweets/geolocated" pathFilter ".*2021\.03\.29.*,.*2021\.03\.30.*,.*2021\.03\.31.*,.*2021\.04\.02.*,.*2021\.04\.04.*,.*2021\.04\.05.*,.*2021\.04\.06.*,.*2021\.04\.07.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-03-30'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt,ar" langNames "English,French,Spanish,Portuguese,Arabic" langPaths "C:/Users/abdou/Documents/Twitter/languages/en.txt.gz,C:/Users/abdou/Documents/Twitter/languages/fr.txt.gz,C:/Users/abdou/Documents/Twitter/languages/es.txt.gz,C:/Users/abdou/Documents/Twitter/languages/pt.txt.gz,C:/Users/abdou/Documents/Twitter/languages/ar.txt.gz"  parallelism 6 params "C:\Users\abdou\AppData\Local\Temp\RtmpqufGC7\repl269c40ae5643.txt" >"C:\Users\abdou\AppData\Local\Temp\RtmpqufGC7\file269c46e345c7"' execution failed with error code 1

Error in b_wincred_i_get(target) : 
  Windows credential store error in 'get': Not enough memory resources are available to complete this operation.

Calls: <Anonymous> ... <Anonymous> -> b_wincred_get_raw -> b_wincred_i_get
Execution halted

**Comment by forchard** [comment]
Hi Abdouzster,
Epitweetr is designed to protect files from corruption when the computer goes down suddenly. But clearly there may still be some unsafe writes to files to fix. 

* Could you confirm if you get the same error when rutnning `epitweetr::setup_config("C:/Users/abdou/Documents/Twitter")`
* If so, we have to identify which is the file that was corrupted, please open an R console and type:
   * `p <- jsonlite::read_json("C:/Users/abdou/Documents/Twitter/properties.json")`
   * `to <- jsonlite::read_json("C:/Users/abdou/Documents/Twitter/topics.json")`
   * `ta <- jsonlite::read_json("C:/Users/abdou/Documents/Twitter/tasks.json")`

Then can you share the file giving an error?

Best,
Francisco

**Comment by Abdouzster** [comment]
No I didn't get the same error with epitweetr::setup_config("C:/Users/abdou/Documents/Twitter")

**Comment by Abdouzster** [comment]
ta <- jsonlite::read_json("C:/Users/abdou/Documents/Twitter/tasks.json")
Error in parse_con(txt, bigint_as_char) : 
  lexical error: invalid char in json text.
                                                            (right here) ------^

**Comment by forchard** [comment]
Great thanks we are getting there,

* Could you share the contents of the file tasks.json to see if there is some parts that can be recovered?
* Could you check if there is a file starting with "~tasks..." on the epitweetr directory? If so can you share it?

Best,
Francisco

**Comment by Abdouzster** [comment]
Here are all files 
the content of the task.json is not readable.  I changed its extension to get Github to accept it
[tasks.txt](https://github.com/EU-ECDC/epitweetr/files/6273619/tasks.txt)
It is not accepting the other ~tasks files: should I do the same for those files to be able to share

**Comment by Abdouzster** [comment]
Here are the other three with txt extension
[~tasks (3).txt](https://github.com/EU-ECDC/epitweetr/files/6273646/tasks.3.txt)
[~tasks.txt](https://github.com/EU-ECDC/epitweetr/files/6273647/tasks.txt)
[~tasks (2).txt](https://github.com/EU-ECDC/epitweetr/files/6273648/tasks.2.txt)

**Comment by forchard** [comment]
Please replace the corrupted tasks.json with the newest copy (it should be ~tasks3 from 24/02/2021) so it is not from today but it should work.
Please let us know how it goes.

@lauespinosa we should try to replicate this error and go into further investigation. Normally saving tasks is using [write_json_atomic](https://github.com/EU-ECDC/epitweetr/blob/98ee5fb3824a2afa501c9900dc710f71e4661772/epitweetr/R/config.R#L625) function that should never produce a corrupted file.

**Comment by Abdouzster** [comment]
Thanks a lot Francisco! It is running now but there is an error with aggregate. I am sharing it below. I will see if it will recover with this run or it will persist.
My nickname is Abdou drop the zster please :)

![image](https://user-images.githubusercontent.com/23038328/113917866-c1b70480-97af-11eb-9b5b-c97d41205d98.png)

**Comment by forchard** [comment]
Those are good new Abdou!!
The error message is just an old error. As you said you should try to run it again and see how it goes.
Please let me know if you still have more issues. We will figure it out.
Best,
Francisco

**Comment by lauespinosa** [comment]
> Please replace the corrupted tasks.json with the newest copy (it should be ~tasks3 from 24/02/2021) so it is not from today but it should work.
> Please let us know how it goes.
> 
> @lauespinosa we should try to replicate this error and go into further investigation. Normally saving tasks is using [write_json_atomic](https://github.com/EU-ECDC/epitweetr/blob/98ee5fb3824a2afa501c9900dc710f71e4661772/epitweetr/R/config.R#L625) function that should never produce a corrupted file.

Indeed, I will try to reproduce this error and add it to the list of improvements
