### ISSUE TITLE
Warning on trying to activate search and detection

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#23]
On the instance that is running on my Azure VM: I get the following warning when I click on the activation buttons for search and detect on the configuration page.

Warning in system(cmd, intern = TRUE) :
  running command 'schtasks /Create /TN "epitweetr_search_loop" /TR "cmd /c C:/PROGRA~1/R/R-40~1.4/bin/Rscript.exe \"C:/Users/azaghlool/epitweetr/search.R\" \"E:/Twitter\" >> \"C:/Users/azaghlool/epitweetr/search.log\" 2>&1" /SC HOURLY /ST 08:42 /SD "mm-dd-yy" /F' had status 16389
Warning in system(cmd, intern = TRUE) :
  running command 'schtasks /Create /TN "epitweetr_detect_loop" /TR "cmd /c C:/PROGRA~1/R/R-40~1.4/bin/Rscript.exe \"C:/Users/azaghlool/epitweetr/detect.R\" \"E:/Twitter\" >> \"C:/Users/azaghlool/epitweetr/detect.log\" 2>&1" /SC HOURLY /ST 08:42 /SD "mm-dd-yy" /F' had status 16389

**Comment by lauespinosa** [comment]
Hi Abdou,

Can you please check if you have two epitweetr tasks in the Task Scheduler? If you have, you don't need to click on 'activate' anymore, you can manage the tasks (search and detection) directly in the Task Scheduler. 

If not, you can try to run the following code in a command prompt (cmd) window:

`schtasks /Create /TN "epitweetr_search_loop" /TR "cmd /c C:/PROGRA1/R/R-401.4/bin/Rscript.exe "C:/Users/azaghlool/epitweetr/search.R" "E:/Twitter" >> "C:/Users/azaghlool/epitweetr/search.log" 2>&1" /SC HOURLY /ST 08:42 /SD "mm-dd-yy" /F`

`schtasks /Create /TN "epitweetr_detect_loop" /TR "cmd /c C:/PROGRA1/R/R-401.4/bin/Rscript.exe "C:/Users/azaghlool/epitweetr/detect.R" "E:/Twitter" >> "C:/Users/azaghlool/epitweetr/detect.log" 2>&1" /SC HOURLY /ST 08:42 /SD "mm-dd-yy" /F`

**Comment by Abdouzster** [comment]
Thanks Laura! 
I activated today from the Task Scheduler. I just wanted to make sure if I need to do something about the warning. 
Abdou

**Comment by lauespinosa** [comment]
Can you please check if you have recent files in the `epitweetr` folder under 'tweets' and 'series'?

Also, remember to refresh the Task Scheduler to ensure the tasks are actually running.

**Comment by Abdouzster** [comment]
I see recent files in these folders.

**Comment by lauespinosa** [comment]
Great, then the tasks are properly running 😃
