### ISSUE TITLE
aggregate error

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#24]
I found the following aggregate error that led to abort  last night:
![image](https://user-images.githubusercontent.com/23038328/114393825-7bbfbf00-9b68-11eb-878e-6f4c437d2e15.png)

Detect file output:

Error in `[[.default`(day_slots[day_slots > tasks[[i]]$scheduled_for],  : 
  subscript out of bounds
Calls: <Anonymous> ... plan_tasks -> [[ -> [[.POSIXct -> .POSIXct -> NextMethod
Execution halted
Error in `[[.default`(day_slots[day_slots > tasks[[i]]$scheduled_for],  : 
  subscript out of bounds
Calls: <Anonymous> ... plan_tasks -> [[ -> [[.POSIXct -> .POSIXct -> NextMethod
Execution halted
Error in `[[.default`(day_slots[day_slots > tasks[[i]]$scheduled_for],  : 
  subscript out of bounds
Calls: <Anonymous> ... plan_tasks -> [[ -> [[.POSIXct -> .POSIXct -> NextMethod
Execution halted
2021-04-11 22:15:03 : Executing task geotag
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
2021-04-11 22:15:06[INFO]---->geolocating tweets for 2021.04.11.00001
21/04/11 22:15:43 WARN BLAS: Failed to load implementation from: com.github.fommil.netlib.NativeSystemBLAS
2021-04-11 22:18:01[INFO]---->geolocation finished successfully
2021-04-11 22:18:07 : Executing task aggregate
Aggregating series country_counts ( 2021-04-06 ) by looking on tweets collected between ( 2021.04.06, 2021.04.07, 2021.04.08, 2021.04.09, 2021.04.11 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
saving  country_counts  data for week 2021.14 , day 2021-04-06
Aggregating series country_counts ( 2021-04-07 ) by looking on tweets collected between ( 2021.04.07, 2021.04.08, 2021.04.09, 2021.04.11 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
saving  country_counts  data for week 2021.14 , day 2021-04-07
Aggregating series country_counts ( 2021-04-08 ) by looking on tweets collected between ( 2021.04.07, 2021.04.08, 2021.04.09, 2021.04.11 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
saving  country_counts  data for week 2021.14 , day 2021-04-08
Aggregating series country_counts ( 2021-04-09 ) by looking on tweets collected between ( 2021.04.08, 2021.04.09, 2021.04.10, 2021.04.11 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
saving  country_counts  data for week 2021.14 , day 2021-04-09
Aggregating series country_counts ( 2021-04-10 ) by looking on tweets collected between ( 2021.04.09, 2021.04.10, 2021.04.11 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
Failed...
failed while serie country_counts for 2021-04-10   simpleWarning in shell(tcmd): '
call "C:\Program Files\Java\jre1.8.0_281\bin\java" -cp "C:/Users/azaghlool/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;E:/Twitter/jars/*" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath "E:/Twitter/tweets/search" geoPath "E:/Twitter/tweets/geolocated" pathFilter ".*2021\.04\.09.*,.*2021\.04\.10.*,.*2021\.04\.11.*" columns "cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original" groupBy "topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code" sortBy "" filterBy "date_format(created_at, 'yyyy-MM-dd') = '2021-04-10'" sourceExpressions "tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc" langCodes "en,fr,es,pt" langNames "English,French,Spanish,Portuguese" langPaths "E:/Twitter/languages/en.txt.gz,E:/Twitter/languages/fr.txt.gz,E:/Twitter/languages/es.txt.gz,E:/Twitter/languages/pt.txt.gz"  parallelism 2 params "C:\Users\AZAGHL~1\AppData\Local\Temp\RtmpEptF3e\replec4257746f3.txt" >"C:\Users\AZAGHL~1\AppData\Local\Temp\RtmpEptF3e\fileec427fe3378"' execution failed with error code 4

**Comment by lauespinosa** [comment]
Hi Abdou,

It seems there is a corrupted file. 
Could it be that the detection pipeline was stopped before getting this error? If so, in which step was it?

Try clicking on 'Run aggregate' and restarting the detection task from the Task Manager.

**Comment by forchard** [comment]
Hi Abdou!
Let's try to find which is the source of the problem. Could you please try the following ?
* **Stop the detection loop**  if running (you can do it from windows task scheduler)
*  Open an R console and type the following commands
    * **Initialize** epitweetr with `epitweetr::setup_config("E:/Twitter") # or whatever your epitweeter folder is`
    *  **Reproduce** the issue with `df <- epitweetr:::get_aggregated_serie("country_counts", "2021-04-10", list("2021.04.09", "2021.04.10", "2021.04.11"))`
* Please share the detailed output.

Best,
Francisco

**Comment by Abdouzster** [comment]
Hi Francisco,
It didn't produce any errors. The result are a list and a data frame.
Here is the console sequence: 
epitweetr::setup_config("E:/Twitter")
> df <- epitweetr:::get_aggregated_serie("country_counts", "2021-04-10", list("2021.04.09", "2021.04.10", "2021.04.11"))
Aggregating series country_counts ( 2021-04-10 ) by looking on tweets collected between ( 2021.04.09, 2021.04.10, 2021.04.11 )
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
> View(t)
> View(df)
Thanks,
Abdelhamid

**Comment by forchard** [comment]
Ok, then maybe the issue could be related (again) with the corruption of the file tasks.json. Could you please check if the file can be properly read with the following commands:
* `epitweetr::setup_config("E:/Twitter") # or whatever your epitweeter folder is`
*  `t <- epitweetr::get_tasks()`

**Comment by Abdouzster** [comment]
Looks fine it didn't show any errors. The task file problem was on the laptop but this error is on the Azure VM

**Comment by forchard** [comment]
but is aggregate still failing? If so can you execute `epitweetr::aggregate_tweets()`

**Comment by Abdouzster** [comment]
No, the aggregate is not failing. It looks like a temporary error. If it repeat with me, I will execute this code for you to know the reason.
Thanks a lot Francisco!
Abdou
