### ISSUE TITLE
Various Issues after running Tweet Search & Detection Pipeline

### ISSUE THREAD

**Issue by HORSE-source** [EU-ECDC/epitweetr#26]
I'm setting up Epitweetr on a colleagues laptop and have gotten as far as running the search and detection pipelines. However, I get the following issue under to the right of "Topics" on the Dash board:

![image](https://user-images.githubusercontent.com/80736892/117522252-201a0300-af67-11eb-872e-3eca1262211a.png)

I check to see if the directory that it's asking for exists, it does not. 

 Furthermore, under "message" in the Detection Pipeline section, I see:

![image](https://user-images.githubusercontent.com/80736892/117522212-e3e6a280-af66-11eb-8c5a-a5eec5700be6.png)

I navigate to the troubleshoot pane and run the diagnostic and I see the following:

![image](https://user-images.githubusercontent.com/80736892/117522237-05478e80-af67-11eb-948d-30d02bb4fb9f.png)

I have also reverenced the Vinnette for Epitweeter and it shows that under the data folder, in this case, 
C:\Users\revir\Documents\epitweetr, that there should be a sub folder labelled "tweets" and in that folder there should be two sub-folders, "search" and "geolocated." I do not see the the geolocated folder, only the "search" folder

![image](https://user-images.githubusercontent.com/80736892/117522397-f57c7a00-af67-11eb-867f-1ebb1bf01cdf.png)

I'm not sure is there is an issue with the .json file, or if this is a machine specific issue. 

Thank you in advance for your time.

**Comment by lauespinosa** [comment]
Dear @HORSE-source ,

It is normal to get those messages in the dashboard, since the detection pipeline has not reached step 'aggregate' yet, which creates the series that are displayed in the dashboard. For the same reason there is no 'geolocated' folder because the 'geotag' step has not been executed yet.

Try clicking on 'run geonames' in the configuration page and ensure the computer is not turned off or put to sleep while executing these tasks.

You can also share the detect.log for a more detailed error message, which you should have in `C:\Users\revir\epitweetr\`.

Best regards,

Laura

**Comment by HORSE-source** [comment]
Good morning Laura!

It's great to hear from you! I have attached the detect.log for your review. In the interim, I will go through and run another instance of epitweetr on my colleague's machine and let it run for 72 hours in hopes that it should be able to create the directories in that amount of time. If there are any additional steps that I may be missing, please let me know. 

As always, it's fantastic to hear from you! 

Tyler 


[detect.log](https://github.com/EU-ECDC/epitweetr/files/6719471/detect.log)

**Comment by lauespinosa** [comment]
Dear Tyler,

It seems the error comes from the subscribers file. It is possible that the alert slots are not included in the correct format. 

You can check how to include this information in the part 2 video of ['Getting to know epitweetr'](https://github.com/EU-ECDC/epitweetr/discussions/6), minute 23:15

**Comment by lauespinosa** [comment]
@HORSE-source , please let us know if the problem was solved and we can close the issue.

**Comment by lauespinosa** [comment]
issue closed since no more feedback was provided by user
