### ISSUE TITLE
Error in initiating epitweetr

### ISSUE THREAD

**Issue by ajarynowski** [EU-ECDC/epitweetr#27]
By trying to run most of epitweetr functions such an error come out:
" epitweetr_app(data_dir = NA)
Error in parse_con(txt, bigint_as_char) : parse error: premature EOF
                                                            (right here) ------^"

I do not know, which file it is parsing. What I previously did:
-entered Twitter API Creditials
- run default epitweetr::search_loop
-  run default epitweetr::detect_loop (which crushed due lack of memory)

**Comment by lauespinosa** [comment]
Dear @ajarynowski ,

When using epitweetr functions, you should run first `epitweetr::setup_config('data_dir')` replacing 'data_dir' by your selected path for epitweetr data (e.g. 'C:/Users/ajarynowski/Documents/epitweetr').

Please let me know if it work fine after running that.

You can also execute epitweetr by launching the Shiny app: `epitweetr::epitweetr_app('data_dir')` also replacing 'data_dir' with your selected path for epitweetr data.

**Comment by ajarynowski** [comment]
Yes, I run it with with epitweetr_app(data_dir ="C:/Users/gulak/Downloads/Nowy folder/asf/korona/shiny/epi"). I just post it without my own directory. App worked before, because I was able to imput my API creditials and start searching.

**Comment by lauespinosa** [comment]
If you execute epitweetr from the app, by running `epitweetr_app("C:/Users/gulak/Downloads/Nowy folder/asf/korona/shiny/epi")` is sufficient for triggering the epitweetr loops (search and detect), regarding the data directory .

However, if you decide to use epitweetr functions, you need to run `setup_config("C:/Users/gulak/Downloads/Nowy folder/asf/korona/shiny/epi")` before running `search_loop()` and `detect_loop()`

**Comment by ajarynowski** [comment]
I found a problem. 

Task.json file was created, but was empty.

**Comment by lauespinosa** [comment]
The tasks.json file is created and updated by the detect loop. Have you been able to run the detect loop? 

Do you have any other file in the same folder starting '~tasks'?

Can you please run the following commands and share the output?
* `setup_config("C:/Users/gulak/Downloads/Nowy folder/asf/korona/shiny/epi")`
* `ta <- jsonlite::read_json("C:/Users/gulak/Downloads/Nowy folder/asf/korona/shiny/epi/tasks.json")`

**Comment by lauespinosa** [comment]
@ajarynowski , please let us know if this issue was solved or if you need further assistance

**Comment by ajarynowski** [comment]
solved


Andrzej Jarynowski
http://interdisciplinaryresearch.eu/przedstawiciele/jarynowski/
