### ISSUE TITLE
Can not open tasks file

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#28]
![error2021-06--15](https://user-images.githubusercontent.com/23038328/122068428-66624d80-cdc2-11eb-9a4c-333406cd7db1.PNG)
I don't know why it can't open the task file. I opened it manually and the file is okay. It has been generating this error since Saturday. I restarted the computer and trying it again. The program looks running for me as the search and detect are activated. No alerts generated since Saturday

**Comment by lauespinosa** [comment]
This 'permission denied' error can appear if there are some admin restrictions to access certain files or if the connection is interrupted (for example, in a virtual machine, this may happen if it goes on sleeping mode or if other user has the file open but the tasks are running under your profile). 

Please check if there are recent files in `E:/Twitter/tweets/search` and `E:/Twitter/series`.

**Comment by Abdouzster** [comment]
There are new files in these directories. It works fine but it this error generated randomly almost on a daily basis. I keep check because of that. I will check for the possibility of sleeping mode. Is there any other reason you might think of?

**Comment by Abdouzster** [comment]
In the backup tasks file (~tasks.json638712d1e62), the following error message appears:
"aggregate": {
    "task": "aggregate",
    "order": 4,
    "started_on": 1618366188154,
    "end_on": 1618365330089,
    "status": "failed",
    "scheduled_for": 1618366188061,
    "message": "failed while serie country_counts for 2021-04-05  languages simpleWarning in shell(tcmd): '\ncall \"C:\\Program Files\\Java\\jre1.8.0_281\\bin\\java\" -cp \"C:/Users/azaghlool/Documents/R/win-library/4.0/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;E:/Twitter/jars/*\" -Dfile.encoding=UTF8 -Xmx2g  org.ecdc.twitter.Tweets getTweets tweetPath \"E:/Twitter/tweets/search\" geoPath \"E:/Twitter/tweets/geolocated\" pathFilter \".*2021\\.04\\.06.*,.*2021\\.04\\.07.*,.*2021\\.04\\.08.*,.*2021\\.04\\.09.*,.*2021\\.04\\.12.*,.*2021\\.04\\.13.*\" columns \"cast(sum(case when is_retweet then 1 else 0 end) as Integer) as retweets||cast(sum(case when is_retweet then 0 else 1 end) as Integer) as tweets||@known_retweets||@known_original\" groupBy \"topic||date_format(created_at, 'yyyy-MM-dd') as created_date||date_format(created_at, 'HH') as created_hour||coalesce(text_loc.geo_country_code, linked_text_loc.geo_country_code) as tweet_geo_country_code||coalesce(place_full_name_loc.geo_country_code, linked_place_full_name_loc.geo_country_code, user_location_loc.geo_country_code, user_description_loc.geo_country_code) as user_geo_country_code\" sortBy \"\" filterBy \"date_format(created_at, 'yyyy-MM-dd') = '2021-04-05'\" sourceExpressions \"tweet||created_at||is_retweet||screen_name||linked_screen_name||tweet_longitude||tweet_latitude||place_longitude||place_latitude||linked_place_longitude||linked_place_latitude|||geo||text_loc||linked_text_loc||user_location_loc||user_description_loc||place_full_name_loc||linked_place_full_name_loc||text_loc||linked_text_loc||place_full_name_loc||linked_place_full_name_loc\" langCodes \"en,fr,es,pt\" langNames \"English,French,Spanish,Portuguese\" langPaths \"E:/Twitter/languages/en.txt.gz,E:/Twitter/languages/fr.txt.gz,E:/Twitter/languages/es.txt.gz,E:/Twitter/languages/pt.txt.gz\"  parallelism 2 params \"C:\\Users\\AZAGHL~1\\AppData\\Local\\Temp\\RtmpG2JncE\\repl6386d407291.txt\" >\"C:\\Users\\AZAGHL~1\\AppData\\Local\\Temp\\RtmpG2JncE\\file638301574cb\"' execution failed with error code 4\n",
    "failures": 0

**Comment by Abdouzster** [comment]
Now it is giving me the same error for another file topics.json
![image](https://user-images.githubusercontent.com/23038328/122607612-daae2280-d048-11eb-902b-b4e165f7a65f.png)

**Comment by lauespinosa** [comment]
The warning for topics.json indicates "permission denied". We have seen a similar warning for the topics file in our virtual machine when we log out. 

It is not an error, it is just indicating that epitweetr app could not connect to a file (either user being logged out, either the file being removed/changed or used by other software).

epitweetr will be running even if the Shiny app is not open. You can close the Shiny app when not using it to avoid these warnings.
