### ISSUE TITLE
warn blas: failed to load implementation from github

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#29]
I am getting the error in the image
![error2021-06-21](https://user-images.githubusercontent.com/23038328/122819664-bbadcb80-d2a8-11eb-9159-fd907948a23f.PNG)

**Comment by lauespinosa** [comment]
The message indicates that Open BLAS is not available. It is used to speed up the geolocation process, but `epitweetr` tasks are running properly.
In other words, it is just a warning, not an error
