### ISSUE TITLE
Detection loop error

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#34]
I have the following error happening from time to time and lead to stopping of detection loop. I am not sure what is the reason  and how to avoid it.
Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
saving  topwords  data for week 2021.35 , day 2021-09-03
2021-09-04 10:44:43 aggregation done!
Error in `[[.default`(day_slots[day_slots > tasks[[i]]$scheduled_for],  : 
  subscript out of bounds
> epitweetr::detect_loop('E:/Twitter')
Error in `[[.default`(day_slots[day_slots > tasks[[i]]$scheduled_for],  : 
  subscript out of bounds

**Comment by lauespinosa** [comment]
The error refers to the scheduled tasks as shown in the code that appears in the error (`day_slots > tasks[[i]]$scheduled_for`). Epitweetr is set up to do the next task according to the status (done, pending, etc).

Next time the error happens, could you please check which are the status of the tasks in the configuration page of the Shiny app?

If one task status is "failed" or "aborted", you can restart it manually by clicking on "Run..." task. If the error happens at the end of the aggregation, it is possibly related to the alert so you can try clicking on "Run alerts" in the configuration page (no need to restart the detection pipeline, it will be restarted automatically about 10 seconds after clicking "Run...").

Have you received the alert emails as usual during this time that this error happens from time to time?

**Comment by forchard** [comment]
Hi @Abdouzster 
My guess is that something unexpected was found on the subcribers .xlx file, the one you have to set up in order to receive emails.
Could you please share the file after removing any personal information?
Best,
Francisco

**Comment by Abdouzster** [comment]
Hi Francisco,
I am currently not using this feature on the Azure VM. The file is the default one.
Thanks,
Abdou

**Comment by forchard** [comment]
Could you please try the following code on your machine on an R session

| epitweetr::setup_config("YOUR_DATA_FOLDER_HERE")
| epitweetr:::get_task_day_slots(epitweetr:::get_tasks()$alerts)

Thanks!
Francisco

**Comment by Abdouzster** [comment]
Here it is:
> epitweetr::setup_config("E:/Twitter")
> epitweetr:::get_task_day_slots(epitweetr:::get_tasks()$alerts)
 [1] "2021-09-12 00:30:00 UTC" "2021-09-12 02:00:00 UTC" "2021-09-12 03:30:00 UTC" "2021-09-12 05:00:00 UTC"
 [5] "2021-09-12 06:30:00 UTC" "2021-09-12 08:00:00 UTC" "2021-09-12 09:30:00 UTC" "2021-09-12 11:00:00 UTC"
 [9] "2021-09-12 12:30:00 UTC" "2021-09-12 14:00:00 UTC" "2021-09-12 15:30:00 UTC" "2021-09-12 17:00:00 UTC"
[13] "2021-09-12 18:30:00 UTC" "2021-09-12 20:00:00 UTC" "2021-09-12 21:30:00 UTC" "2021-09-12 23:00:00 UTC"
[17] "2021-09-13 00:30:00 UTC"

**Comment by Abdouzster** [comment]
I usually click Run geo and run the detection again to make it work epitweetr::detect_loop('E:/Twitter')

**Comment by forchard** [comment]
Thanks Abdouster!
@lauespinosa  I have created a new branch "#issue34" and a pull request #35 
I have not yet been able to test the fix.
Do you have a data folder v0 to test it?
Thanks!

**Comment by Abdouzster** [comment]
Hi Francisco,
I don't have a data folder v0
Thanks,
Abdou

**Comment by forchard** [comment]
No worries @Abdouzster that was a comment for @lauespinosa, I have implemented a fix, we are going through deployment process
