### ISSUE TITLE
Can't run geonames

### ISSUE THREAD

**Issue by romanceline** [EU-ECDC/epitweetr#4]
Hi,

I have been trying to use the tool but in the detection pipeline, when i try to 'run geonames', it always end up with an abortion and the following message 'Max number of retries reached assembling'

(Java is installed and the variable JAVA_HOME is set)

Any idea what might be the problem?

Many thanks in advance :)

**Comment by lauespinosa** [comment]
Please check that epitweetr is not trying to use more cores ('**Spark cores**' in the _Configuration_ page of epitweetr app) than those available in your machine, which can be the cause of the issue. By default, it is set up to 4.

The number of cores available depends on the capacity of your machine, including other tasks not related to epitweetr being processed in parallel.

**Comment by forchard** [comment]
Hi Romanceline!
Have you seen the issues reported on the **diagnostic tab** could you please share them with us?
That's a good start for fixing the issue.
Best,
Francisco

**Comment by romanceline** [comment]
Hi both,

Thanks a lot for your quick replies.
The number of spark cores is set to 2 and the diagnostic tab mentions 'geonames has not been indexed. Please execute the geonames task'.
When i run the task, it actually stays quite a long time on 'status: running, message: assembling', then gets aborted.

Best,

Celine

**Comment by forchard** [comment]
Are all checks before geonames in green then? If not please send the error status.

If you are running on windows and you have activated the detect loop using the shiny app then there is a log file that should tell you more details. it is the **detect.log** located on c:\Users\youtUser\epitweetr\detect.log, could you see if there is an error message on that file ans share it with us? (you can attach the entire file if you prefer)

Best,
Francisco

**Comment by romanceline** [comment]
All checks before geonames are green yes, apart from 'tweets', which i guess is normal until the other ones are green?
Remaining checks after geonames are red though.
I can't see the detect.log file. I could only see 'detect.bat' and 'detect.sh' inside the 'devscripts' folder but i guess that's not what you are looking for?

**Comment by forchard** [comment]
Are you looking on c:\Users\youtUser\epitweetr\detect.log?

**Comment by forchard** [comment]
Also could you please kindly tell us 
- how you have installed epitweetr?
- how you have launched the app? 
- how you have activated the search and detect loop?
Best,
Francisco

**Comment by romanceline** [comment]
Oh sorry, i was looking in the wrong place indeed.
I'm attaching the file.
I downloaded epitweetr trough the Rstudio console with install.packages('epitweetr').
I then launched the app with 'epitweetr_app('MyDataFolder') and i activated the search and detect loop in the 'configuration' tab.
[detect.log](https://github.com/EU-ECDC/epitweetr/files/5457288/detect.log)

**Comment by forchard** [comment]
Ok, here some more questions

1. What windows version you are using?
1. Could you please share the search.log too?
1. Is your machine running Hadoop/Spark?
1. Can you see any .json.gz file on C:\Users\romanc\Desktop\R\Scripts\EpiTweeterData\tweets\search\Dengue\

Thanks!
Francisco

**Comment by romanceline** [comment]
Sure, I am using Windows 10 and I attach the search.log [search.log](https://github.com/EU-ECDC/epitweetr/files/5457502/search.log)
I saw in the documentation that epitweetr would download automatically the external dependencies. I just checked that the url's mentioned in the configuration tab were the same as mentioned in the documentation but i haven't done anything else about hadoop/spark. 

There is indeed a file in the Dengue folder: 2020.10.22.00001.json.gz. which i assume was generated on the 22th of October (in the meantime, I limited the search to Measles and Rubella).

Thanks so much for helping me!

**Comment by forchard** [comment]
Can you please try the following code on an R console?
- epitweetr::setup_config("C:/Users/romanc/Desktop/R/Scripts/EpiTweeterData")
- epitweetr:::spark_job(paste("updateGeonames", epitweetr:::conf_geonames_as_arg(), "assemble", paste("\"TRUE\"",sep=""), "index", paste("\"FALSE\"",sep=""), "parallelism", epitweetr:::conf$spark_cores))

then wait and send te output?
Best
Francisco

**Comment by romanceline** [comment]
What kind of output should i have?
It processed for quite a long time and i got this line:
'Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties'

**Comment by forchard** [comment]
At the end it should just finish or return an error, you can see the progress at http://localhost:4040
As it is running, do you see the size of the following **folder contents** evolving in size?
C:\\Users\\romanc\\Desktop\\R\\Scripts\\EpiTweeterData\\geo
Best,
Francisco

**Comment by forchard** [comment]
Also can you share your machine specs: RAM, memory, and available disk space? On my laptop this command takes less than 10 minutes.

**Comment by romanceline** [comment]
Yes i could see the folder you mentioned growing and it has now a sub-folder 'all-geos.parquet.index' which wasn't there before. 
The geonames task is working perfectly now, it switched to green, thanks again so much. Next ones are on their way :)
Here are my specs:
![image](https://user-images.githubusercontent.com/48318414/97575288-ce5b5380-19ec-11eb-8eaa-5529091c61fe.png)
And i still have 139Gb free out of 269Gb on my disk.

**Comment by forchard** [comment]
Please let us know once you start seen reports data. If you still find issues, maybe there are some permission differences when you run the commands interactively and from the task scheduler.
Best,
Francisco

**Comment by romanceline** [comment]
It's up and running! Amazing work and support :)

Best,

Celine

**Comment by forchard** [comment]
The issue was fixed, but not enough information to reproduce or understand it was provided.
