### ISSUE TITLE
task schedular

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#51]
I deleted epitweetr tasks from task schedular. Is there a way to put it back there?

**Comment by forchard** [comment]
Hi @Abdouzster 
Why did you delete them, by mistake or because there were some process running you could not stop?
In order to recreate the tasks you can click on the activate buttons on the epitweetr configuration page for each task.
Good luck!

**Comment by Abdouzster** [comment]
I clicked on the activation button but it didn't work
