### ISSUE TITLE
Email setting problem

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#53]
I keep getting email alerts failer with the setting in the attached image. I have two ways of authentication with Gmail account. I am not sure if that would be the cause. However, I tried using a yahoo account but still didn't work.
![emailsettingonepitweetr](https://user-images.githubusercontent.com/23038328/157762435-335c7f00-d371-4373-b7d8-943ec3e133cf.png)
e

**Comment by lauespinosa** [comment]
The error may be related to the list of subscribers or to the email authentication. 

For Gmail accounts, you need to allow for less secure apps in the settings of your account. This may apply as well in Yahoo accounts. 

Could you please share the error you get?

**Comment by forchard** [comment]
Hi @Abdouzster 
Less secure apps will stop working from [30 of may 2022](https://support.google.com/accounts/answer/6010255?hl=en#zippy=%2Cif-less-secure-app-access-is-off-for-your-account%2Cuse-an-app-password) 

The way to go would be to use an App password on your google account https://support.google.com/accounts/answer/185833 to get the alerts.

Epitweetr uses emayili to send emails. Do you have the latest version of this package?
You can use this code snippet to test email functionality and get more details on the error:

> epitweetr::setup_config("your data folder here")
> \`%>%\` <- magrittr::\`%>%\`
> dest = "your@email.here"
> html <- "\<html\>\<body\>\<table style=\\"border:1px solid black;width:100%;border-collapse:collapse;background-color:#BBBBBB\\"\>\<tr\>\<td\>Column 1\</td\>\<td\>Column 2\</td\>\</tr\>\</table\>\</body\>\</html\>"
> msg <- (emayili::envelope() %>% emayili::from(epitweetr:::conf$smtp_from) %>% emayili::to(dest) %>% emayili::subject("Hi there!") %>% emayili::html(html))
> smtp <- emayili::server(host = epitweetr:::conf$smtp_host, port=epitweetr:::conf$smtp_port, username=epitweetr:::conf$smtp_login, insecure=epitweetr:::conf$smtp_insecure, password=epitweetr:::conf$smtp_password, reuse = FALSE)
> smtp(msg, verbose = TRUE)

Please let us know how it goes.
Best,
Francisco

**Comment by forchard** [comment]
HI @Abdouzster 
Do you still have this issue?
Best,
Francisco

**Comment by Abdouzster** [comment]
I am sure it is still there. Currently, I am not using the email alert. It would need some collaboration from our IT for the VM setting I think. I don't have time for doing this now. We can close it and may be reopen if I need some support later.
