### ISSUE TITLE
Error with alert detection

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#55]
This error persisting since yesterday 
note: the application had unplanned shutdown then I got the tasks.json problem and then this problem
2022-03-14 09:05:05 : Executing task alerts
Adding topwords
trying URL 'http://localhost:8080/aggregate?jsonnl=true&serie=topwords&topic=Haemorrhagic%20fever%3BMERS-CoV&from=2022-03-13&to=2022-03-13'
Content type 'application/json' length unknown
downloaded 1.1 MB

Failed...
failed while processing  : Error in readRDS(tail(list.files(file.path(conf$data_dir, "series"), full.names = TRUE, : bad 'file' argument

2022-03-14 09:08:46 : Executing task alerts
Cannot determine the last aggregated period for alert detection, tryng again in 0  seconds
Cannot determine the last aggregated period for alert detection, tryng again in 10  seconds
Cannot determine the last aggregated period for alert detection, tryng again in 20  seconds
Cannot determine the last aggregated period for alert detection, tryng again in 30  seconds
Failed...
failed while processing  : Error in do_next_alerts(tasks): Cannot determine the last aggregated period for alert detection. Please check that series have been aggregated

2022-03-14 09:09:52 : Executing task alerts
Adding topwords
trying URL 'http://localhost:8080/aggregate?jsonnl=true&serie=topwords&topic=Bioterrorism%3BSARS&from=2022-03-14&to=2022-03-14'
Content type 'application/json' length unknown
downloaded 54 KB

Failed...
failed while processing  : Error in readRDS(tail(list.files(file.path(conf$data_dir, "series"), full.names = TRUE, : bad 'file' argument

2022-03-14 09:11:47 : Executing task alerts
Adding topwords
trying URL 'http://localhost:8080/aggregate?jsonnl=true&serie=topwords&topic=Bioterrorism%3BSARS&from=2022-03-14&to=2022-03-14'
Content type 'application/json' length unknown
downloaded 54 KB

Failed...
failed while processing  : Error in readRDS(tail(list.files(file.path(conf$data_dir, "series"), full.names = TRUE, : bad 'file' argument

**Comment by forchard** [comment]
Hi Abdouzster,
I am trying to allocate some tile to analyze this issue. 
Did you manage to make your epitweetr installation work again after migration?
Best,
Francisco

**Comment by Abdouzster** [comment]
Hi Forchard,
Yes, it is working after "migration". I would not really call it migration after getting rid of old data. It is working now and producing alerts. I opened another issue about email alert as it is not working for me to the contrary of the previous version.
Thanks,
Abdelhamid

**Comment by Abdouzster** [comment]
Hi Francisco,
I am not sure why some of the topics are not collecting any data. whenever I explore those on the dashboard there is no data.
