### ISSUE TITLE
The graph on the dashboard is not displaying the curve 

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#57]
The trending curve is not displayed but the top word and location display. please take a look to the image
![image](https://user-images.githubusercontent.com/23038328/160725583-ee258109-dc0d-4ab5-8286-60085efe9089.png)

**Comment by forchard** [comment]
I guess the issue here is because you are selecting a single day on the period. 
Is the problem still happening when you select more than one day?
All the best!
Francisco

**Comment by Abdouzster** [comment]
Good eye! but I didn't select one day. I left it as 7 days. I don't know how it turned up this way.
It works when it is 7 days
Thanks, 
Abdelhamid
