### ISSUE TITLE
Issue with search/detection

### ISSUE THREAD

**Issue by stonehc** [EU-ECDC/epitweetr#59]
I have changed the topics and set the search and detection to 90 days; however, it is only searching through the past 2 consistently. Is there something I am missing?

**Comment by lauespinosa** [comment]
The span included in the configuration page refers to the time between each loop of search and detection pipelines. Those 90 refer to 90 minutes (i.e., the pipelines will start again every 90 minutes in case they have finalised before that time).
Epitweetr uses the Standard Search API (version 1.1) and Search Tweets (version 2) which allows to retrieve tweets from maximum the past 7 days.
In case of very popular topics, epitweetr may not be able to retrieve all tweets from past 7 days.
