### ISSUE TITLE
Changing my VM login

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#63]
Hi 
I am changing my VM login (username). I am getting this message on the new username.
Listening on http://127.0.0.1:3232
Warning in system(cmd, intern = TRUE) :
  running command 'schtasks /Create /TN "epitweetr_fs_loop" /TR "cmd /c C:/PROGRA~1/R/R-41~1.3/bin/Rscript.exe \"C:/Users/dev_abdelhamid.zaghl/epitweetr/fs.R\" \"E:/Twitter2022\" >> \"C:/Users/dev_abdelhamid.zaghl/epitweetr/fs.log\" 2>&1" /SC HOURLY /ST 10:48 /SD "04/29/2022" /F' had status 1
Should I do something about it?
Thanks,
Abdelhamid

**Comment by Abdouzster** [comment]
I had to run the loops manually

**Comment by forchard** [comment]
I guess this error appears when yo try to activate tasks with the new users right?

1. If you change the user on your VM you would need to delete the previous scheduled tasks (on the task scheduler) then you can activate them again.
2. What is the error message if you run the command in error on a Windows terminal?
> schtasks /Create /TN "epitweetr_fs_loop" /TR "cmd /c C:/PROGRA1/R/R-411.3/bin/Rscript.exe "C:/Users/dev_abdelhamid.zaghl/epitweetr/fs.R" "E:/Twitter2022" >> "C:/Users/dev_abdelhamid.zaghl/epitweetr/fs.log" 2>&1" /SC HOURLY /ST 10:48 /SD "04/29/2022" /F'

We may get details on the error by doing this.

Best,
Francisco

**Comment by Abdouzster** [comment]
Yes I don't have this problem anymore
