### ISSUE TITLE
detection aborted

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#66]
The detection  was aborted with this error:
Max number of retries reached failed while processing alerts Error in checkForRemoteErrors(val): 2 nodes produced errors; first error: cannot allocate vector of size 32.0 Mb

Does not want to work again
![image](https://user-images.githubusercontent.com/23038328/168610036-1b695353-7df6-4bbc-b9f0-791aded26c31.png)

**Comment by forchard** [comment]
Hi @Abdouzster 
Your machine seems to be getting out of memory in R. Alert calculation is performed in parallel on v2 of epitweetr using the same number of processes as defined on spark cores.

1. How much memory and CPU has your VM?
2. What is the setting for spark cores on the configuration page 
3. What is the setting for spark memory on the configuration page

There are too ways to solve this :
1. Decreasing a bit the spark settings would make epitweetr less likely to get out-of-memory exceptions but tasks could take longer to finish.
2. Temporarily increase your VM RAM and see if this error disappears.

Let us know how it goes.
Best,
Francisco 

I think you are running on Windows, can you please add a performance monitor for RAM and CPU? Please see this: https://www.instantfundas.com/2012/03/how-to-record-cpu-and-memory-usage-over.html

**Comment by Abdouzster** [comment]
I will try to get those answers but it seems that I was able to foul the application by editing the tasks file

**Comment by Abdouzster** [comment]
intel xeon platinum 8272cl cpu 2.60GH
8 GB memeory
Spark core is 2
Spark memory is 4g
If it happen again, what spark setting you would suggest

**Comment by forchard** [comment]
Please let us know if the problem reproduce itself. 
Setting the performance monitor monitoring is always a good idea :-)
How many cores do you have?

**Comment by Abdouzster** [comment]
It does not show. I have to ask support
![image](https://user-images.githubusercontent.com/23038328/168642399-9b219631-6b17-4db5-8a7e-8b3180ce017d.png)

**Comment by forchard** [comment]
You have 4 cores (virtual processors).
- My first try would be to get 12GB of RAM with the same settings.
- If not possible you could try to reduce the number of cores to 1 and GB to 3 but I fear geolocation to be too slow with just one core (json files on geo folder may get too big)
- A last option would be to add a configuration setting on epitweetr to choose to reduce the level of parallelism for alert detection itself. Then you could only set that setting to 1 core.

Best,
Francisco
