### ISSUE TITLE
Geoname Aborted

### ISSUE THREAD

**Issue by eunyhwang** [EU-ECDC/epitweetr#70]
Dear Epitweetr Team, 

I had already succeeded to run GeoNames, but today, all of sudden, I kept receiving this error and geonames got aborted:
Max number of retries reached failed while assembling geonames Error in spark_job(paste("updateGeonames", conf_geonames_as_arg(), "assemble", : Error encountered while exeuting: "C:\Program Files\AdoptOpenJDK\jre-8.0.292.10-hotspot\\bin\java" -cp "C:/Users/HwangE/Anaconda3/envs/epit_trial/lib/R/library/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;epit_trial_final//jars/*" -Xmx4g org.ecdc.twitter.Tweets updateGeonames geonamesSource "epit_trial_final//geo/allCountries.txt" geonamesDestination "epit_trial_final//geo" geonamesSimplify "TRUE" assemble "TRUE" index "FALSE" parallelism 2 

I saw some people also got this error, but it seems not clear that how it had been solved. 

When I check the terminal, there's an error saying (is this related to the error above?): 
ERROR Shell: Failed to locate the winutils binary in the hadoop binary path
java.io.IOException: Could not locate executable null\bin\winutils.exe in the Hadoop binaries.

It's still confusing since I already had got this error before and solved it by setting the path with  
"Sys.setenv(HADOOP_HOME = "C:/myPath/hadoop")"

Any help or advice will be appreciated!

Cheers, 
Eunyoung

**Comment by forchard** [comment]
Hi @eunyhwang 
These Paths seems wrong:
- C:/Users/HwangE/Anaconda3/envs/epit_trial/lib/R/library/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;epit_trial_final//jars
- epit_trial_final//geo/allCountries.txt

Can you share the command you use to run epitweetr? There may be an issue on the epitweetr_home path.

Best,
Francisco

**Comment by eunyhwang** [comment]
Dear @forchard

sorry for the late reply!

I used an autonomous device as I wanted to see if the issue was due to proxy, but I came across to the same error. 

This is the error message on Configuration tab:
failed while assembling geonames Error in spark_job(paste("updateGeonames", conf_geonames_as_arg(), "assemble", : Error encountered while exeuting: "C:\Program Files\Java\jre1.8.0_321\bin\java" -cp "C:/Users/User/anaconda3/envs/epit_trial/lib/R/library/epitweetr/java/ecdc-twitter-bundle_2.12-1.0.jar;epit_trial/jars/*" -Xmx4g org.ecdc.twitter.Tweets updateGeonames geonamesSource "epit_trial/geo/allCountries.txt" geonamesDestination "epit_trial/geo" geonamesSimplify "TRUE" assemble "TRUE" index "FALSE" parallelism 2 

And this is the commend when I run epitweetr:
(epit_trial) C:\Users\User\hwange>r                                                                                                                                                                                                             R version 4.1.3 (2022-03-10) -- "One Push-Up"                                                                                                                                                                                                                                                                                    > library(epitweetr)                                                                                                    
> epitweetr_app("epit_trial") 

I also manually set the path again using this:
Sys.setenv(HADOOP_HOME= "C:/Users/User/hwange/epit_trial/hadoop")

Best, 
Eunyoung

**Comment by eunyhwang** [comment]
Dear @forchard,

True, I didn't put the full path. When I replace it with the full path like this ('C:/mydirect/epitweetr'), it perfectly worked!
You can close this issue, thank you!

Best, 
Eunyoung
