### ISSUE TITLE
Geonames download error

### ISSUE THREAD

**Issue by rzaha** [EU-ECDC/epitweetr#72]
![image](https://user-images.githubusercontent.com/93827052/180317099-e8d883c9-fe20-4a0a-b939-226309601e21.png)

Hi,

i tried several times to install the application but i suffer from the above error.
i run the link for all countries 
increasing the timeout to 240 after a message appear in the console that reached the max time which is 60 sec.
any help?
i updated the version of R studio to Rstudio pro, R to 4.1 version and Java on the latest update.

**Comment by rzaha** [comment]
![image](https://user-images.githubusercontent.com/93827052/180317801-35947b98-7f20-4303-b868-09d0bd4afbda.png)

**Comment by rzaha** [comment]
![image](https://user-images.githubusercontent.com/93827052/180318890-b6e3142d-be33-43cd-8165-cfeb9d1ba71b.png)

**Comment by rzaha** [comment]
@forchard any help ??

**Comment by dmorenofernandez** [comment]
Hello,

I had similar issues as you are experiencing.
Try increasing timeout (more than you did) and download methor

options(timeout=100000)
options(download.file.method = "auto")

Regards

**Comment by lauespinosa** [comment]
@rzaha , please let us know if the issue was solved with the suggestion provided by @dmorenofernandez

**Comment by forchard** [comment]
I have another workaround.... I have the same issue last week.
1. In the configuration page you can download the list of available language. Do it.
2. Open the excel file and find the language you are looking for. Copy the URL
3. Download the file manually on your browser
4. Update the excel file with the local paths on the format "file://c:/your path lo file here"
5. Upload de file with the local paths
6. Run the languages task manually

Hope this will help!
Best,
Francisco

**Comment by madonna-10** [comment]
Hello epitweetr team, when I tried to download the file manually I got this message
Bad or illegal path
