### ISSUE TITLE
Error in Create_topwords

### ISSUE THREAD

**Issue by eunyhwang** [EU-ECDC/epitweetr#75]
I ran the _create_topwords_ function with the line below:
_epitweetr::create_topwords(topic = "dengue", country_codes = c("FR", "CL",  "AU"), date_min="2022-07-01", date_max="2022-07-22",with_retweets = FALSE, location_type="tweet", top=25)_

And this error occurred:
_Error in if (conf$onthefly_api) jsonlite::stream_in(url(q_url), verbose = FALSE) else { : 
argument is of length zero_

What does the error exactly mean and is there a way to solve it?

Thank you for your assist in advance!

Best, 
Eunyoung

**Comment by forchard** [comment]
Hi @eunyhwang sorry for the late reply, I was on summer break
Some basic information can help us to find the issue:
1. Can you see the topwords report on the shiny app?
2. Is the database and the data collection tasks running?
3. Did you manage to successfully run the tasks "depenencies", "geonames" and "languages"

Thanks for trying epitweetr!
Best,
Francisco

**Comment by forchard** [comment]
Alright, have you added the line
setup_config("your data folder here")
before calling create_topwords?

Best,
Francisco

**Comment by eunyhwang** [comment]
I ran the line before I called the function "update_geonames" a long time ago and thought it needs to be run once.. Do you think I still need to add the line?

Best,
Eunyoung

**Comment by forchard** [comment]
Each time you start a session that will call epitweetr functions, you have to run setup_config to load the configuration settings from the data folder. As its description says "Load epitweetr application settings from the designated data directory"
I hops this will help!
Best,
Francisco

**Comment by eunyhwang** [comment]
Ah okay, but what do you mean by each time? For example, if I manually run detect_loop, search_loop,  and fs_loop in a each terminal, should I add the line for each time? 

Best, 
Eunyoung

**Comment by forchard** [comment]
These functions have the data_dir as a parameter if you use it then you do not have to call the setup_config, otherwise you have.
Best,
Francisco

**Comment by eunyhwang** [comment]
It worked perfectly, thank you for your support!

**Comment by forchard** [comment]
you are welcome!
