### ISSUE TITLE
Error in get_token

### ISSUE THREAD

**Issue by Haouurra** [EU-ECDC/epitweetr#77]
Greetings, 
I am running the shiny app for the first time, after clicking on the buttons “Run dependencies”, “Run geonames” and “Run languages”, and choosing "User account" in the Twitter authentication method, I am not being directed to the Twitter homepage for authentication. Note that I run the command "auth_setup_default()" to set the twitter account signed in as the default account, I am having the below warning:
Warning: Error in get_token: Cannot get a token. Please create it from the configuration page. 
When trying to "Run diagnostics" in the Troubleshoot page I am having the below error: 
Cannot get a token. Please create it from the configuration page

**Comment by Haouurra** [comment]
@forchard Kindly advise. 

It seems token has not been created as well.
![image](https://user-images.githubusercontent.com/114404833/193564177-464199c9-860c-4a16-8200-617e7480dd4f.png)

**Comment by lauespinosa** [comment]
@Haouurra, please ensure you have clicked on "Save settings" after selecting Twitter User account in the configuration page. 

After that, you need to activate the tasks on the left side "epitweetr database", "Data collection & processing" and "Requirements & alerts" as indicated in the user documentation. At some point during the dependencies download, you may be required to stop the epitweetr database.

The Twitter token won't be created if you don't start collecting tweets by launching the "Data collection & processing" task

**Comment by Haouurra** [comment]
Greetings, 

Thanks for your reply. 
I am clicking on the Save settings. 
Today the dependencies showed an "aborted" status, although I referred to another issue, where they suggested to add the below lines of code to increase timeout
options(timeout=100000)
options(download.file.method = "auto")

Only Requirements & alerts seem to be running, epitweetr database is Stopped and Data collection & processing as well. 

![aborted](https://user-images.githubusercontent.com/114404833/195075133-ca0e0231-069a-4fdd-983e-283bd0e7c814.png)

**Comment by forchard** [comment]
Hi @Haouurra 
Please see #72 I proposed a workaround for downloading big files manually when your internet connection is not stable.
Concerning your issue with the token I think you are using a new version of rtweet package that is incompatible with the current release

**Comment by lauespinosa** [comment]
Solution was provided and it worked for other users. Since there is no further inputs on this regard, I am closing this comment
