### ISSUE TITLE
Installing old version

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#79]
I shared the data from the old version of epitweetr with another group and they were trying to install the old version to use it to extract trends. They were not able to install it.
Here are the statements:

install.packages("devtools")
library(devtools)
# installing epitweetr
install_version("epitweetr", version = "0.1.28", repos = "http://cran.us.r-project.org")  

epitweetr_app("\\Ncr-a_hecsbc5s\\HECSBC5\\SHARED\\ORS\\Surveillance Unit\\Ep$

> Error in epitweetr_app("\\Ncr-a_hecsbc5s\\HECSBC5\\SHARED\\ORS\\Surveillance Unit\\EpiTweet Data-April2022") :
  could not find function "epitweetr_app"
> library(epitweetr)
Error in library(epitweetr) : there is no package called 'epitweetr'

**Comment by forchard** [comment]
Hi @Abdouzster 
I have tried on my environment and the istallation of the old version works using devtools 
Please check if there is any error after 

> install_version..

Best,
Francisco
