### ISSUE TITLE
Apache Commons Text 

### ISSUE THREAD

**Issue by Abdouzster** [EU-ECDC/epitweetr#83]
Is epitweetr using Apache Commons Text? I am getting request from Azure security that I have to update its version because of vulnerability. Is it part of epitweetr package? how to update that

**Comment by forchard** [comment]
Hi @Abdouzster 
Thanks for reporting this security issue. Indeed, Apache commons text is an indirect dependency of epitweetr.
We have updated the jar version on the development version of epitweetr.
Once it is released you will be able to install it from CRAN. 
Then you would need to run the task 'update dependencies'

Best,
Francisco

**Comment by Abdouzster** [comment]
I am not sure if it is released yet. I re installed the package again yesterday. would this update be included?

**Comment by lauespinosa** [comment]
The latest release from December 2022 has the updated jar version.

**Comment by Abdouzster** [comment]
I installed the new package but it didn't fix this. I am not sure how to fix it on the VM. Any advice? would it need to remove everything and reinstall?

**Comment by lauespinosa** [comment]
You will need to delete the jar folder and download the dependencies again. If the folder already exist, epitweetr will not download it again automatically, even if there are new versions of the dependencies
