### ISSUE TITLE
get_token deprecated

### ISSUE THREAD

**Issue by icrescio** [EU-ECDC/epitweetr#84]
I'm trying to setting up my credentials in Windows11, R 4.2.2, and this warning is raised:
Warning: `get_token()` was deprecated in rtweet 1.0.0.
ℹ Please use `auth_get()` instead.
ℹ The deprecated feature was likely used in the epitweetr package.
  Please report the issue at
  <https://github.com/EU-ECDC/epitweetr/issues>.
as required I report the issue.

Anyway, I'm still not able to set up my credentials: R is busy from a long time (hours) but nothing is happening

**Comment by forchard** [comment]
Hi @icrescio ,
We are aware of the problem and it id fixed on our development branch, it should be available on CRAN soon.
In the meantime, your only solution is to manually downgrade rtweet to a version before 1.0.0.
Please let us know if you find more issues after that,
Best, 
Francisco

**Comment by icrescio** [comment]
Solved thank you!
